name = "steal-the-sun"
author = "mexasae86 & INiKkEI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d291de713b00f123137bbb47c9a66e0eb5d0ce4b96f51dde6bdef350f246a50e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
