name = "steal-the-sun"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18f443fb3cafd1c72c905bd42071d3c6eb4db92ce5e12836bee8449fb9cef659"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
