name = "steal-the-sun"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c230fcf87ea7a0476efb317b6e91e23bd992ccbda6a6cfd84803fb16cad2b97d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
