[stage]
id = "steel_autocannon"
display_name = "Steel Autocannon"
description = "Longest barrel (6) — the heaviest setup, demands serious stress just to turn on mount."
icon = "createbigcannons:steel_autocannon_recoil_spring"
unlock_message = "Steel Autocannon is unlocked! Full weight, full commitment."
dependency = ["steel_cannon","bronze_autocannon"]

[recipes]
locked_items = [
	"createbigcannons:steel_autocannon_breech",
    "createbigcannons:steel_autocannon_recoil_spring",
    "createbigcannons:steel_autocannon_barrel",
    "createbigcannons:unbored_steel_autocannon_breech",
    "createbigcannons:unbored_steel_autocannon_recoil_spring",
    "createbigcannons:unbored_steel_autocannon_barrel",
    "createbigcannons:incomplete_steel_autocannon_breech",
    "createbigcannons:incomplete_steel_autocannon_recoil_spring",
    "createbigcannons:steel_autocannon_breech_extractor"
]
always_unlocked = []